/**
 * client App Styles
 *
 * Purpose: client App Styles — Feature module for Coach Connect.
 * Why it matters: Keeps feature logic out of screens so auth, nutrition, and trainer rules stay consistent.
 * Area: src/client
 * Key exports: CARD_GAP, SCREEN_WIDTH, STATS_ROW_PAD_H, STATS_ROW_CARD_GAP
 *
 * @file-header
 */
import { StyleSheet, Dimensions, Platform } from 'react-native';

export const CARD_GAP = 16;
export const SCREEN_WIDTH = Dimensions.get('window').width;
export const STATS_ROW_PAD_H = 40;
export const STATS_ROW_CARD_GAP = 12;

const clientAppStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
  },
  safeAreaLight: {
    backgroundColor: '#FFFFFF',
  },
  safeAreaDark: {
    backgroundColor: '#0A0A0A',
  },
  scrollView: {
    flex: 1,
  },
  // ─────────────────────────────────────────────
  // HERO (Client + Trainer top-of-app)
  // ─────────────────────────────────────────────
  heroOuter: {
    marginHorizontal: 22,
    marginTop: 0,
    marginBottom: 6,
    borderRadius: 24,
    borderWidth: 1,
    backgroundColor: 'transparent',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.14,
    shadowRadius: 24,
    elevation: 10,
  },
  heroBorderGradient: {
    borderRadius: 24,
    padding: 2,
  },
  heroInner: {
    borderRadius: 23,
    overflow: 'hidden',
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  heroContentRow: {
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  heroLeft: {
    alignItems: 'center',
  },
  welcomeWrap: {
    alignItems: 'center',
    marginBottom: 4,
  },
  welcomeKicker: {
    fontSize: 18,
    fontWeight: '800',
    letterSpacing: 2.5,
  },
  welcomeUnderline: {
    marginTop: 6,
    width: 72,
    height: 3,
    borderRadius: 99,
    opacity: 0.9,
  },
  heroTitle: {
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: -0.5,
  },
  heroTagline: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 1.5,
  },
  heroRight: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroRightInlineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    width: '100%',
  },
  heroInlineQuoteWrap: {
    flex: 1,
    marginLeft: 12,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  heroInlineQuoteBorder: {
    borderRadius: 28,
    padding: 1,
    alignSelf: 'stretch',
    justifyContent: 'center',
  },
  heroQuotePillWrap: {
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroQuotePillBorder: {
    borderRadius: 28,
    padding: 1,
    alignSelf: 'center',
    width: '92%',
    maxWidth: 360,
  },
  auroraBorder: {
    height: 160,
    marginHorizontal: 16,
    marginTop: 0,
    marginBottom: 16,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,107,157,0.25)',
    backgroundColor: 'transparent',
  },
  auroraContainer: {
    flex: 1,
    borderRadius: 22,
    overflow: 'hidden',
  },
  logoCardInner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: 'rgba(255,107,157,0.08)',
    borderRadius: 16,
  },
  logoMark: {
    width: 88,
    height: 88,
    borderRadius: 20,
    marginBottom: 16,
  },
  logoTitle: {
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: 3,
    color: '#FFFFFF',
  },
  logoSubtitle: {
    marginTop: 6,
    fontSize: 12,
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 1.5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#0A0A0A',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: 'white',
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: 16,
    position: 'relative',
  },
  themeToggleText: {
    fontSize: 20,
    color: 'white',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.6)',
    marginTop: 16,
    fontFamily: 'System',
  },
  lottieAnimation: {
    width: '100%',
    height: '100%',
  },
  lightText: {
    color: '#000000',
  },
  darkText: {
    color: '#FFFFFF',
  },
  lightMutedText: {
    color: '#6B7280',
  },
  cardShadowWrap: {
    borderRadius: 12,
    shadowColor: '#A855F7',
    shadowOffset: { width: 0, height: 18 },
    shadowOpacity: 0.28,
    shadowRadius: 28,
    elevation: 14,
    backgroundColor: 'transparent',
  },
  cardShadowWrapLight: {
    shadowColor: '#5E5CE6',
    shadowOpacity: 0.18,
  },
  lightCard: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  photoScrollView: {
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  addPhotoButton: {
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: '#1F2937',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#4B5563',
  },
  addPhotoButtonLight: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  addPhotoText: {
    marginTop: 8,
    fontSize: 12,
    color: '#9CA3AF',
  },
  videoRailContainer: {
    height: 180,
    backgroundColor: '#0A0A0A',
    overflow: 'visible',
  },
  videoRailContainerLight: {
    backgroundColor: '#FFFFFF',
  },
  videoRailContent: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  videoRailItem: {
    width: 120,
    height: 160,
    marginRight: 12,
    borderRadius: 18,
    overflow: 'hidden',
    position: 'relative',
  },
  videoRailVideo: {
    width: '100%',
    height: '100%',
  },
  videoRailOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.18)',
  },
  statsRowWrap: {
    paddingTop: 2,
    marginTop: 8,
  },
  statsRowContent: {
    paddingHorizontal: 20,
    paddingBottom: 6,
    gap: 12,
  },
  statCardShadow: {
    borderRadius: 24,
    marginRight: 12,
    shadowOffset: { width: 0, height: 16 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
    elevation: 10,
    overflow: 'visible',
  },
  statCardBlur: {
    borderRadius: 24,
    overflow: 'hidden',
    width: '100%',
    alignSelf: 'stretch',
  },
  statCardInner: {
    borderRadius: 24,
    padding: 14,
    borderWidth: 1,
    minHeight: 150,
    width: '100%',
    alignSelf: 'stretch',
    alignItems: 'stretch',
    justifyContent: 'space-between',
  },
  /** Wellness row: stack title + value as one centered group (no space-between gap). */
  statCardInnerCentered: {
    justifyContent: 'center',
    gap: 10,
  },
  statWellnessValueBlock: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 2,
  },
  statWellnessEmpty: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 6,
    paddingVertical: 4,
  },
  statKicker: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.8,
    textAlign: 'center',
    width: '100%',
  },
  statBig: {
    fontSize: 22,
    fontWeight: '800',
    marginTop: 10,
    lineHeight: 26,
  },
  statEmpty: {
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  statEmptyRow: {
    marginTop: 10,
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
  },
  statEmptyCopy: {
    flex: 1,
    minWidth: 0,
    paddingRight: 10,
    justifyContent: 'center',
  },
  statEmptyLottie: {
    width: 100,
    height: 100,
  },
  statEmptyLottieSmall: {
    width: 64,
    height: 64,
    opacity: 0.8,
    marginRight: -4,
  },
  wellnessEmptyLottie: {
    width: 80,
    height: 80,
  },
  wellnessEmptyLottieSmall: {
    width: 56,
    height: 56,
    opacity: 0.8,
    marginRight: -2,
  },
  statWellnessEmptyRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 6,
    paddingVertical: 6,
  },
  wellnessEmptyCta: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  statEmptyText: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  statEmptyCta: {
    marginTop: 6,
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
  },
  statGradientBlock: {
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    alignSelf: 'stretch',
  },
  statGradientNumberWrap: {
    paddingVertical: 4,
  },
  statGradientNumber: {
    fontSize: 48,
    fontWeight: '800',
    lineHeight: 54,
    textAlign: 'center',
  },
  statGradientLabel: {
    marginTop: 6,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
    width: '100%',
  },
  statGradientWorkoutText: {
    fontSize: 34,
    lineHeight: 38,
    fontWeight: '800',
    textAlign: 'center',
  },
  statCtaBtn: {
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 14,
  },
  statCtaText: {
    fontWeight: '800',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  waterRow: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  waterMeta: {
    marginLeft: 12,
  },
  waterNumber: {
    fontSize: 26,
    fontWeight: '900',
    lineHeight: 30,
  },
  waterUnit: {
    marginTop: 2,
    fontSize: 12,
    fontWeight: '700',
  },
  sleepWrap: {
    marginTop: 12,
  },
  sleepTop: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  sleepNumber: {
    fontSize: 28,
    fontWeight: '900',
    lineHeight: 32,
  },
  sleepMoon: {
    marginLeft: 8,
    fontSize: 20,
    fontWeight: '800',
  },
  sleepUnit: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: '700',
  },
  goalWrap: {
    marginTop: 12,
  },
  goalLabel: {
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 20,
  },
  goalBarTrack: {
    marginTop: 10,
    height: 8,
    borderRadius: 999,
    overflow: 'hidden',
  },
  goalBarFill: {
    height: '100%',
    borderRadius: 999,
  },
  goalPct: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: '700',
  },
  goalEmpty: {
    marginTop: 12,
    flex: 1,
    justifyContent: 'center',
  },
  goalOutlineBtn: {
    marginTop: 10,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderWidth: 1,
    alignSelf: 'flex-start',
  },
  goalOutlineText: {
    fontSize: 12,
    fontWeight: '800',
  },
  greetingSection: {
    paddingHorizontal: 20,
    paddingTop: 10,
    paddingBottom: 6,
    overflow: 'visible',
    alignItems: 'center',
  },
  greetingLineWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  greetingTitle: {
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  greetingCardOuter: {
    marginTop: 14,
    paddingHorizontal: 16,
  },
  greetingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  greetingQuoteCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 24,
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderWidth: 1,
  },
  greetingQuoteCardDark: {
    backgroundColor: '#050509',
    borderColor: '#27272f',
  },
  greetingQuoteCardLight: {
    backgroundColor: '#F3F4F6',
    borderColor: '#E5E7EB',
  },
  greetingQuote: {
    flex: 1,
    paddingRight: 16,
  },
  greetingQuoteText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#E5E7EB',
    lineHeight: 26,
  },
  greetingQuoteAuthor: {
    marginTop: 10,
    fontSize: 13,
    fontWeight: '500',
    color: '#9CA3AF',
  },
  greetingLottieWrap: {
    width: 96,
    height: 96,
    borderRadius: 20,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 16,
  },
  greetingLottie: {
    width: '100%',
    height: '100%',
  },
  welcomeCard: {
    width: 140,
    minHeight: 74,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.12)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.22,
    shadowRadius: 18,
    elevation: 8,
  },
  welcomeCardLight: {
    borderColor: 'rgba(0, 0, 0, 0.08)',
  },
  welcomeText: {
    fontSize: 16,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.92)',
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  welcomeTextLight: {
    color: 'rgba(15, 23, 42, 0.9)',
  },
  lottieWrap: {
    width: 140,
    height: 140,
    marginLeft: 16,
    borderRadius: 20,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lottieWrapLight: {
    // keep neutral in light mode; no override needed
  },
  calendarContainer: {
    paddingHorizontal: 20,
    marginVertical: 10,
  },
  gradientCardBorder: {
    borderRadius: 16,
    padding: 1.5,
  },
  weekCalendar: {
    backgroundColor: '#020617',
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: '#4B5563',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.28,
    shadowRadius: 22,
    elevation: 10,
  },
  weekHeader: {
    marginBottom: 12,
  },
  weekHeaderText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  weekDays: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  weekDay: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    minWidth: 40,
  },
  weekDayToday: {
    backgroundColor: '#BF5AF2',
  },
  weekDayName: {
    fontSize: 12,
    color: '#9CA3AF',
    marginBottom: 4,
  },
  weekDayNumber: {
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
  weekDayNumberToday: {
    color: 'white',
  },
  lightWeekDay: {
    backgroundColor: '#F3F4F6',
  },
  trainerButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 999,
    width: '100%',
    maxWidth: 300,
    alignItems: 'center',
  },
  trainerButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  trainerButtonTextLight: {
    color: 'black',
    fontWeight: '600',
    fontSize: 14,
    letterSpacing: 0.5,
  },
  notificationBadge: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
  },
  notificationBadgeText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  sectionTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 2,
    textTransform: 'uppercase',
    marginBottom: 12,
  },
  agendaContainer: {
    paddingHorizontal: 20,
    marginTop: 10,
    marginBottom: 22,
  },
  agendaGradientBorder: {
    borderRadius: 16,
    overflow: 'hidden',
  },
  agendaGradientBorderPremiumEmpty: {
    borderRadius: 22,
    overflow: 'hidden',
  },
  agendaCardInnerPremiumEmpty: {
    borderRadius: 20.5,
    overflow: 'hidden',
  },
  agendaBgPremiumEmpty: {
    borderRadius: 20.5,
    minHeight: 200,
  },
  agendaEmptyAmbient: {
    ...StyleSheet.absoluteFillObject,
    opacity: 1,
  },
  agendaEmptyPremiumShell: {
    marginTop: 14,
    marginBottom: 4,
  },
  agendaEmptyGlass: {
    borderRadius: 18,
    borderWidth: 1,
    paddingVertical: 16,
    paddingHorizontal: 16,
    overflow: 'hidden',
  },
  agendaEmptyPremiumRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 4,
  },
  agendaEmptyIconRingOuter: {
    width: 62,
    height: 62,
    borderRadius: 31,
    padding: 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  agendaEmptyIconRingInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  agendaEmptyCopyCol: {
    flex: 1,
    marginLeft: 14,
    paddingTop: 2,
  },
  agendaEmptyHeadline: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.2,
    lineHeight: 22,
  },
  agendaEmptySubcopy: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
  },
  agendaBadgeEmptyPremium: {
    borderWidth: 1,
    borderColor: 'rgba(109, 40, 217, 0.28)',
  },
  agendaCardInner: {
    borderRadius: 14,
    overflow: 'hidden',
    // Inner wrapper for animated card; background is handled by gradients inside.
    padding: 0,
  },
  agendaBg: {
    borderRadius: 14,
    overflow: 'hidden',
    minHeight: 120,
  },
  agendaTexture: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.55,
  },
  agendaPad: {
    padding: 20,
  },
  agendaHeaderRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  agendaSubtitle: {
    fontSize: 12,
    fontWeight: '400',
    color: '#B0B0B0',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
  },
  agendaTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.2,
  },
  agendaTitleRow: {
    marginTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  agendaTitleIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  agendaBadge: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.14)',
  },
  agendaBadgeText: {
    color: '#FFFFFF',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  agendaExercisesWrap: {
    marginTop: 16,
    gap: 12,
  },
  agendaExerciseRowPremium: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  agendaDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginTop: 6,
    backgroundColor: 'rgba(255,255,255,0.16)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.18)',
  },
  agendaExerciseName: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  agendaExerciseSets: {
    marginTop: 3,
    fontSize: 13,
    fontWeight: '400',
    color: '#B0B0B0',
  },
  agendaFooterRow: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
  },
  agendaDuration: {
    fontSize: 12,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.78)',
  },
  agendaTimestamp: {
    fontSize: 11,
    fontWeight: '400',
    color: '#B0B0B0',
  },
  agendaEmptyPremium: {
    fontSize: 13,
    fontWeight: '600',
  },
  agendaCardDark: {
    backgroundColor: 'rgba(31, 41, 55, 0.95)',
    borderWidth: 0,
  },
  agendaCardLight: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderWidth: 0,
  },
  agendaEmptyContent: {
    paddingVertical: 20,
    alignItems: 'center',
    gap: 14,
  },
  agendaEmptyText: {
    fontSize: 14,
    textAlign: 'center',
  },
  agendaEmptyButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
  },
  agendaEmptyButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
  },
  agendaWorkoutBlock: {
    marginBottom: 16,
  },
  agendaWorkoutHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingRight: 8,
  },
  agendaWorkoutTitle: {
    fontSize: 16,
    fontWeight: '700',
    flex: 1,
  },
  agendaExercisesList: {
    paddingLeft: 32,
    paddingTop: 4,
    gap: 6,
  },
  agendaExerciseRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  agendaExerciseNum: {
    fontSize: 12,
    width: 20,
    fontWeight: '600',
  },
  agendaExerciseText: {
    fontSize: 13,
    flex: 1,
  },
  agendaCard: {
    backgroundColor: '#1F2937',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#4B5563',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.28,
    shadowRadius: 22,
    elevation: 10,
  },
  agendaItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#4B5563',
  },
  agendaItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#6B7280',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  checkedBox: {
    backgroundColor: '#22C55E',
    borderColor: '#22C55E',
  },
  workoutName: {
    fontSize: 14,
    color: 'white',
  },
  workoutNameChecked: {
    textDecorationLine: 'line-through',
    color: '#9CA3AF',
  },
  workoutSets: {
    fontSize: 12,
    color: '#9CA3AF',
    fontFamily: 'monospace',
  },
  nutritionContainer: {
    paddingHorizontal: 20,
    marginTop: 12,
    marginBottom: 22,
  },
  nutritionGradientBorder: {
    borderRadius: 16,
    padding: 2,
    overflow: 'hidden',
  },
  nutritionCard: {
    backgroundColor: '#1F2937',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
    padding: 14,
  },
  nutritionCardLight: {
    backgroundColor: '#F3F4F6',
    borderColor: 'rgba(255,107,157,0.25)',
  },
  nutritionGrid2x2: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  nutritionGridCell: {
    width: '50%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 4,
  },
  nutritionCompactCirclesRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 6,
  },
  nutritionCompactCircleCell: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  nutritionCircleWrap: {
    alignItems: 'center',
    position: 'relative',
  },
  nutritionCircleCenter: {
    position: 'absolute',
    left: 0,
    right: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  nutritionCircleValue: {
    fontSize: 15,
    fontWeight: '700',
  },
  nutritionCircleLabel: {
    fontSize: 11,
    fontWeight: '600',
  },
  macrosGrid: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  macroItem: {
    alignItems: 'center',
    flex: 1,
    minWidth: 0,
    paddingHorizontal: 2,
  },
  macroIcon: {
    width: 55,
    height: 55,
    resizeMode: 'contain',
  },
  macroLabel: {
    fontSize: 16,
    textShadowColor: 'cyan',
    color: '#9CA3AF',
    marginTop: 2,
  },
  macroValue: {
    fontSize: 14,
    fontWeight: '600',
    color: 'white',
    marginTop: 1,
  },
  additionalNutrientsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
    paddingHorizontal: 4,
  },
  additionalNutrientItem: {
    alignItems: 'center',
    width: '22%',
    minWidth: 60,
    paddingHorizontal: 2,
    paddingVertical: 4,
  },
  additionalNutrientIcon: {
    fontSize: 16,
    marginBottom: 2,
  },
  additionalNutrientLabel: {
    fontSize: 10,
    color: '#9CA3AF',
    marginTop: 1,
    textAlign: 'center',
  },
  additionalNutrientValue: {
    fontSize: 11,
    fontWeight: '600',
    color: 'white',
    marginTop: 1,
    textAlign: 'center',
  },
  caloriesSection: {
    marginBottom: 8,
  },
  caloriesInfo: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  caloriesLabel: {
    fontSize: 13,
    color: '#9CA3AF',
  },
  caloriesValue: {
    fontSize: 14,
    fontWeight: '600',
    color: 'white',
  },
  progressBarBackground: {
    height: 8,
    backgroundColor: '#374151',
    borderRadius: 4,
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    borderRadius: 4,
  },
  journalLink: {
    fontSize: 13,
    color: '#BF5AF2',
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 8,
  },
  notesContainer: {
    paddingHorizontal: 20,
    marginTop: 20,
    paddingBottom: 100,
  },
  notesGradientBorder: {
    borderRadius: 16,
    padding: 2,
    overflow: 'hidden',
    ...(Platform.OS === 'ios' && { shadowColor: '#a855f7', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.2, shadowRadius: 12 }),
    elevation: 4,
  },
  notesCardInner: {
    borderRadius: 14,
    overflow: 'hidden',
    padding: 16,
  },
  notesCardDark: {
    backgroundColor: 'rgba(20, 25, 40, 0.95)',
  },
  notesCardLight: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  notesEmptyContent: {
    paddingVertical: 40,
    alignItems: 'center',
    gap: 14,
  },
  notesEmptyText: {
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
  },
  notesEmptySubtext: {
    fontSize: 14,
    textAlign: 'center',
    lineHeight: 20,
    paddingHorizontal: 20,
  },
  notesContent: { gap: 28 },
  notesSection: { gap: 14 },
  notesCategoryTitle: {
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.5,
    marginBottom: 4,
    marginTop: 4,
    textTransform: 'uppercase',
  },
  notesSectionTitle: {
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  notesNoteCard: {
    borderWidth: 1,
    borderRadius: 16,
    padding: 16,
    gap: 8,
    backgroundColor: 'rgba(255,255,255,0.03)',
  },
  notesNoteText: { fontSize: 15, lineHeight: 22 },
  notesNoteDate: { fontSize: 12, fontWeight: '500' },
  notesMediaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  notesMediaCard: {
    width: '31%',
    alignItems: 'center',
    gap: 6,
  },
  notesMediaThumb: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 14,
    backgroundColor: 'rgba(0,0,0,0.2)',
    borderWidth: 0.5,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  notesVideoPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.3)',
  },
  notesMediaLabel: { fontSize: 12, fontWeight: '500' },
  notesDocRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    backgroundColor: 'rgba(255,255,255,0.02)',
  },
  notesDocName: { fontSize: 15, fontWeight: '600', marginBottom: 4 },
  notesFileInfo: { flex: 1, justifyContent: 'center', minWidth: 0 },
  notesFileMeta: { fontSize: 12, fontWeight: '500', color: 'rgba(255,255,255,0.5)' },
  notesCard: {
    backgroundColor: '#1F2937',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  notesGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  fileItem: {
    alignItems: 'center',
  },
  centerNavItem: {
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  fileIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 8,
    backgroundColor: '#374151',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fileLabel: {
    fontSize: 12,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 8,
  },
  emptyStateContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 32,
  },
  emptyStateText: {
    color: '#9CA3AF',
    marginTop: 12,
    textAlign: 'center',
  },
  emptyStateButton: {
    marginTop: 16,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 999,
  },
  emptyStateButtonText: {
    color: 'white',
    fontWeight: '600',
    fontSize: 14,
  },
  glassCard: {
    borderRadius: 24,
    overflow: 'hidden',
    position: 'relative',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  glassCardBorder: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    pointerEvents: 'none',
  },
  heroCardContainer: {
    marginBottom: 20,
    borderRadius: 24,
    overflow: 'hidden',
  },
  heroGradientBorder: {
    borderRadius: 24,
    padding: 1,
  },
  heroCard: {
    borderRadius: 24,
    padding: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
  },
  heroHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  heroTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
    fontFamily: 'System',
  },
  aiBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: 'rgba(108, 92, 231, 0.2)',
    alignSelf: 'flex-start',
  },
  aiBadgeText: {
    fontSize: 10,
    fontWeight: '500',
    color: '#6C5CE7',
    letterSpacing: 0.3,
    fontFamily: 'System',
  },
  heroWorkoutName: {
    fontSize: 24,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
    fontFamily: 'System',
  },
  heroSubtitle: {
    fontSize: 15,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.6)',
    marginBottom: 20,
    lineHeight: 20,
    fontFamily: 'System',
  },
  heroStats: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
  },
  heroStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  heroStatText: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.6)',
    fontFamily: 'System',
  },
  heroButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 24,
    backgroundColor: '#6C5CE7',
  },
  heroButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    fontFamily: 'System',
  },
  caloriesCard: {
    marginBottom: CARD_GAP,
  },
  caloriesContent: {
    padding: 24,
  },
  caloriesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  caloriesHeroLabel: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 1,
    marginBottom: 8,
    fontFamily: 'System',
  },
  caloriesHeroValue: {
    fontSize: 40,
    fontWeight: '700',
    color: '#FFFFFF',
    fontFamily: 'System',
    letterSpacing: -0.5,
  },
  caloriesGoal: {
    fontSize: 20,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  caloriesFooter: {
    flexDirection: 'row',
    gap: 20,
  },
  caloriesStat: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  caloriesStatText: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  smallStatCard: {
    // Inherits from GlassCard
  },
  smallStatContent: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  smallStatIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  smallStatIconImage: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  smallStatValue: {
    fontSize: 24,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
    fontFamily: 'System',
  },
  smallStatLabel: {
    fontSize: 11,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 0.5,
    fontFamily: 'System',
  },
  gridContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: CARD_GAP,
  },
  gridCard: {
    // Inherits from GlassCard
  },
  gridContent: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  gridIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  gridIconImage: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  gridTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
    textAlign: 'center',
    fontFamily: 'System',
  },
  gridSubtitle: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    textAlign: 'center',
    fontFamily: 'System',
  },
  upcomingSection: {
    marginBottom: 24,
  },
  upcomingContainer: {
    padding: 4,
  },
  upcomingItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.05)',
  },
  upcomingIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  upcomingContent: {
    flex: 1,
  },
  upcomingTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
    marginBottom: 4,
    fontFamily: 'System',
  },
  upcomingTime: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  emptyState: {
    padding: 24,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  emptyStateText: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    paddingLeft: 4,
  },
  sectionAccent: {
    width: 2,
    height: 16,
    backgroundColor: '#8B7FFF',
    marginRight: 8,
    borderRadius: 1,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.5)',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    fontFamily: 'System',
  },
  discoverSection: {
    marginBottom: 24,
  },
  discoverGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: CARD_GAP,
  },
  discoverCard: {
    // Inherits from GlassCard
  },
  discoverContent: {
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  discoverIconContainer: {
    width: 64,
    height: 64,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  discoverIconImage: {
    width: 32,
    height: 32,
    resizeMode: 'contain',
  },
  discoverTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
    textAlign: 'center',
    fontFamily: 'System',
  },
  discoverSubtitle: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    textAlign: 'center',
    fontFamily: 'System',
  },
  findTrainersSection: {
    marginBottom: 24,
  },
  findTrainersContent: {
    padding: 20,
  },
  findTrainersHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  findTrainersIcon: {
    width: 40,
    height: 40,
    marginRight: 12,
  },
  findTrainersTextContainer: {
    flex: 1,
  },
  findTrainersTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
    fontFamily: 'System',
  },
  findTrainersSubtitle: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  searchBarContainer: {
    marginTop: 8,
  },
  searchBarGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 16,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(108, 92, 231, 0.3)',
  },
  searchBarPlaceholder: {
    fontSize: 15,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  crmCard: {
    // Inherits from GlassCard
  },
  crmContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    height: '100%',
  },
  crmIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: 'rgba(108, 92, 231, 0.2)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
  },
  crmTextContainer: {
    flex: 1,
  },
  crmTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
    fontFamily: 'System',
  },
  crmSubtitle: {
    fontSize: 13,
    fontWeight: '400',
    color: 'rgba(255,255,255,0.5)',
    fontFamily: 'System',
  },
  // Skeleton loading styles
  skeletonBlock: {
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    opacity: 0.7,
  },
  skeletonCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    borderRadius: 16,
    opacity: 0.7,
  },
});


export default clientAppStyles;
