#!/usr/bin/env node
/**
 * Regenerate src/CODEBASE_GUIDE.md — full file catalog (path + purpose only).
 * No rename suggestions.
 *
 *   node scripts/appendSrcInventoryToGuide.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'src', 'CODEBASE_GUIDE.md');

const EXT = /\.(jsx?|mjs|cjs|json)$/i;

function walk(dir, out = []) {
  const full = path.join(ROOT, dir);
  if (!fs.existsSync(full)) return out;
  for (const name of fs.readdirSync(full)) {
    if (name === 'node_modules' || name.startsWith('.')) continue;
    const rel = path.join(dir, name);
    const stat = fs.statSync(path.join(ROOT, rel));
    if (stat.isDirectory()) walk(rel, out);
    else if (EXT.test(name)) out.push(rel.replace(/\\/g, '/'));
  }
  return out;
}

function parsePurpose(content, rel) {
  const header = content.slice(0, 1200);
  const purposeMatch = header.match(/\*\s*Purpose:\s*(.+?)(?:\n|\*)/s);
  if (purposeMatch) {
    let p = purposeMatch[1].replace(/\s+/g, ' ').trim();
    p = p.replace(/^UI screen or component:\s*/i, '');
    p = p.replace(/\s*— Feature module for Coach Connect\.?$/i, '');
    if (p.length > 180) p = `${p.slice(0, 177)}…`;
    return p;
  }
  const areaMatch = header.match(/\*\s*Area:\s*(.+?)(?:\n|\*)/);
  if (areaMatch) return `Module in ${areaMatch[1].trim()}.`;
  const base = path.basename(rel);
  if (base.includes('Screen')) return 'Screen component.';
  if (base.includes('Modal')) return 'Modal UI component.';
  if (/Service|Api|Helpers?\.js$/i.test(base)) return 'Service / API helper module.';
  if (/test|spec/i.test(base)) return 'Test or fixture file.';
  return 'Source module.';
}

function groupKey(rel) {
  const parts = rel.replace(/^src\//, '').split('/');
  if (parts.length <= 2) return parts[0] || 'src';
  return `${parts[0]}/${parts[1]}`;
}

function buildGuide(files) {
  const groups = new Map();
  for (const rel of files.sort()) {
    const key = groupKey(rel);
    if (!groups.has(key)) groups.set(key, []);
    const content = fs.readFileSync(path.join(ROOT, rel), 'utf8');
    groups.get(key).push({ rel, purpose: parsePurpose(content, rel) });
  }

  let md = `# Coach Connect — Source File Catalog

Generated by \`node scripts/appendSrcInventoryToGuide.mjs\`. **${files.length} files** under \`src/\`.

Each entry: what the file does. No rename advice. Firebase project ID stays \`anatrox-auth\`.

---

`;

  for (const [group, entries] of [...groups.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    md += `## \`${group}/\`\n\n`;
    md += '| File | What it does |\n|------|-------------|\n';
    for (const { rel, purpose } of entries) {
      const name = rel.replace(/^src\//, '');
      const safePurpose = purpose.replace(/\|/g, '\\|').replace(/\n/g, ' ');
      md += `| \`${name}\` | ${safePurpose} |\n`;
    }
    md += '\n';
  }

  md += `---

*Regenerate anytime: \`node scripts/appendSrcInventoryToGuide.mjs\`*
`;
  return md;
}

const files = walk('src');
fs.writeFileSync(OUT, buildGuide(files));
console.log(`Wrote ${OUT} (${files.length} files)`);
