#!/usr/bin/env node
/**
 * Append one section to CHECKPOINT_COMPARE_LEDGER.txt (never overwrites prior sections).
 *
 * Usage:
 *   node scripts/appendCheckpointLedgerSection.mjs --file /path/to/section.txt
 *   node scripts/appendCheckpointLedgerSection.mjs --stdin   # paste section, Ctrl-D
 *
 * The ledger keeps <<<APPEND_HERE>>> as the last line; new content is inserted above it.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const LEDGER = path.join(__dirname, '..', 'docs/chat-history-recovery/CHECKPOINT_COMPARE_LEDGER.txt');
const SENTINEL = '<<<APPEND_HERE>>>';
const HEADER = `Coach Connect checkpoint ledger (append-only — one section per Cursor chat)

Do not edit this file with the Write tool. Append only via:
  node scripts/appendCheckpointLedgerSection.mjs --file <section.txt>

${SENTINEL}
`;

async function readStdin() {
  const chunks = [];
  for await (const chunk of process.stdin) chunks.push(chunk);
  return Buffer.concat(chunks).toString('utf8').trim();
}

function ensureLedger() {
  if (!fs.existsSync(LEDGER)) {
    fs.writeFileSync(LEDGER, HEADER, 'utf8');
    return;
  }
  const cur = fs.readFileSync(LEDGER, 'utf8');
  if (!cur.includes(SENTINEL)) {
    const trimmed = cur.trimEnd();
    fs.writeFileSync(LEDGER, `${trimmed}\n\n${SENTINEL}\n`, 'utf8');
  }
}

function append(section) {
  const body = String(section || '').trim();
  if (!body) {
    console.error('Nothing to append (empty section).');
    process.exit(1);
  }
  if (!body.includes('END SECTION')) {
    console.error('Section must end with a line: END SECTION');
    process.exit(1);
  }

  ensureLedger();
  const cur = fs.readFileSync(LEDGER, 'utf8');
  if (!cur.includes(SENTINEL)) {
    console.error('Ledger missing sentinel — fix manually or delete ledger and retry.');
    process.exit(1);
  }

  const updated = cur.replace(SENTINEL, `${body}\n\n${SENTINEL}`);
  if (updated === cur) {
    console.error('Append failed — sentinel not replaced.');
    process.exit(1);
  }

  fs.writeFileSync(LEDGER, updated, 'utf8');
  const count = (updated.match(/^={80}$/gm) || []).length;
  console.log(`Appended section to ${LEDGER} (approx ${count} section blocks).`);
}

const args = process.argv.slice(2);
const fileIdx = args.indexOf('--file');
if (fileIdx >= 0 && args[fileIdx + 1]) {
  const section = fs.readFileSync(path.resolve(args[fileIdx + 1]), 'utf8');
  append(section);
} else if (args.includes('--stdin')) {
  const section = await readStdin();
  append(section);
} else {
  console.error(`Usage:
  node scripts/appendCheckpointLedgerSection.mjs --file section.txt
  node scripts/appendCheckpointLedgerSection.mjs --stdin`);
  process.exit(1);
}
