/** React Navigation route names — keep stable for deep linking stubs. */

export const CLIENT_ROUTES = {
  MainTabs: 'ClientMainTabs',
  Home: 'ClientHome',
  Dashboard: 'ClientDashboard',
  Files: 'ClientFiles',
  Nutrition: 'ClientNutrition',
  AI: 'ClientAI',
  Profile: 'ClientProfile',
  Settings: 'ClientSettings',
  HelpFAQ: 'ClientHelpFAQ',
  Terms: 'ClientTerms',
  Privacy: 'ClientPrivacy',
  ContactSupport: 'ClientContactSupport',
  BugReport: 'ClientBugReport',
  WorkoutPlan: 'ClientWorkoutPlan',
  TrainerSearch: 'ClientTrainerSearch',
  TrainerProfile: 'ClientTrainerProfile',
  WeeklyReport: 'ClientWeeklyReport',
  PhotoGallery: 'ClientPhotoGallery',
  AIWorkouts: 'ClientAIWorkouts',
  PlanViewer: 'ClientPlanViewer',
  AIChat: 'ClientAIChat',
};

export const TRAINER_ROUTES = {
  Main: 'TrainerMain',
  Profile: 'TrainerProfile',
  Settings: 'TrainerSettings',
  HelpFAQ: 'TrainerHelpFAQ',
  Terms: 'TrainerTerms',
  Privacy: 'TrainerPrivacy',
  ContactSupport: 'TrainerContactSupport',
  BugReport: 'TrainerBugReport',
  Nutrition: 'TrainerNutrition',
  VoiceAI: 'TrainerVoiceAI',
  TrainerSearch: 'TrainerSearch',
  WeeklyReport: 'TrainerWeeklyReport',
  WorkoutPlan: 'TrainerWorkoutPlan',
  ManualPlanBuilder: 'TrainerManualPlanBuilder',
  AIChat: 'TrainerAIChat',
  PhotoGallery: 'TrainerPhotoGallery',
  AIWorkouts: 'TrainerAIWorkouts',
  WorkoutGenerator: 'TrainerWorkoutGenerator',
  PlanViewer: 'TrainerPlanViewer',
  Payments: 'TrainerPayments',
};
